@baseURL = http://localhost:3000/api/recipes

### GET / db recipes

GET {{baseURL}}

### POST / db recipes
POST {{baseURL}}
Content-Type: application/json

{
    "id": 4124 ,
    "title": "Test POST Recipe",
    "image": "https://source.unsplash.com/random/200×300",
    "summary": "lorem ipsum blablabla ....",
    "sourceUrl": "https://developer.mozilla.org/de/",
    "missedIngredients": [
      {
        "name": "oil"
      }
    ]
}

### DELETE / db delete recipes

DELETE {{baseURL}}
Content-Type: application/json

{
  "_id": "624f13da6f51bc1f8443fccd"
}