@baseURL = http://localhost:3000/api/recipes

### GET / db recipes

GET {{baseURL}}
Authorization: Bearer access toke

### POST / db recipes
POST {{baseURL}}
Content-Type: application/json

{
    "id": 4124 ,
    "title": "Test POST Recipe",
    "image": "https://source.unsplash.com/random/200×300",
    "summary": "lorem ipsum blablabla ....",
    "sourceUrl": "https://developer.mozilla.org/de/",
    "missedIngredients": [
      {
        "name": "oil"
      }
    ]
}

### DELETE / db delete recipes

PATCH  {{baseURL}}/delete
Authorization: Bearer access token
Content-Type: application/json

{
  "title": "Nori Seaweed Muffins"
}

### patch to User.recipes

PATCH {{baseURL}}
Authorization: Bearer access token
Content-Type: application/json

{
    "id": 4124 ,
    "title": "Test POST Recipe",
    "image": "https://source.unsplash.com/random/200×300",
    "summary": "lorem ipsum blablabla ....",
    "sourceUrl": "https://developer.mozilla.org/de/",
    "missedIngredients": [
      {
        "name": "oil"
      }
    ]
}
