### Say hello  

GET http://localhost:3000/api/hello

### Say hello to Jane

GET http://localhost:3000/api/hello/Jane

### login with password and name

POST http://localhost:3000/api/login
Content-Type: application/json

{"name": "Jane", "password": ""}

### Get profile via access token

GET http://localhost:3000/api/profile
Authorization: Bearer ..

### Github request access token

POST https://github.com/login/oauth/access_token
Content-Type: application/json
Accept: application/json

{
    "client_id": "",
    "client_secret": "",
    "code": ""
}

### Get logged in github user

GET https://api.github.com/user
Authorization: Bearer access_token